/* =========================================================
   RULES DATA
   Content for four of the five entries inside the "Rules"
   dropdown in the Reference pane — Skills by Ability, Creature
   Types by Skill, Cover, and Obscured. (The fifth entry,
   Jumping, has a live calculator built from real inputs/buttons,
   so it stays hand-written directly in index.html rather than
   living here as data — see id="dropJumping" there.) Same
   {intro, entries:[{id, title, html}]} shape as the other
   *-data.js files; dm-screen.js reads this and builds the
   actual dropdown elements on page load via renderRulesSection().
   ========================================================= */

const RULES_DATA = {"intro": "", "entries": [
  {"id": "dropSkills", "title": "Skills by Ability", "html": "<p><strong class=\"skill-label-large\"><a href=\"#\" class=\"gloss-ref\" data-ref=\"glossary-strength\">Strength</a>:</strong> <a href=\"#\" class=\"gloss-ref skill-italic\" data-ref=\"glossary-athletics\">Athletics</a></p><p><strong class=\"skill-label-large\"><a href=\"#\" class=\"gloss-ref\" data-ref=\"glossary-dexterity\">Dexterity</a>:</strong> <a href=\"#\" class=\"gloss-ref skill-italic\" data-ref=\"glossary-acrobatics\">Acrobatics</a>, <a href=\"#\" class=\"gloss-ref skill-italic\" data-ref=\"glossary-sleight-of-hand\">Sleight of Hand</a>, <a href=\"#\" class=\"gloss-ref skill-italic\" data-ref=\"glossary-stealth\">Stealth</a></p><p><strong class=\"skill-label-large\"><a href=\"#\" class=\"gloss-ref\" data-ref=\"glossary-intelligence\">Intelligence</a>:</strong> <a href=\"#\" class=\"gloss-ref skill-italic\" data-ref=\"glossary-arcana\">Arcana</a>, <a href=\"#\" class=\"gloss-ref skill-italic\" data-ref=\"glossary-history\">History</a>, <a href=\"#\" class=\"gloss-ref skill-italic\" data-ref=\"glossary-investigation\">Investigation</a>, <a href=\"#\" class=\"gloss-ref skill-italic\" data-ref=\"glossary-nature\">Nature</a>, <a href=\"#\" class=\"gloss-ref skill-italic\" data-ref=\"glossary-religion\">Religion</a></p><p><strong class=\"skill-label-large\"><a href=\"#\" class=\"gloss-ref\" data-ref=\"glossary-wisdom\">Wisdom</a>:</strong> <a href=\"#\" class=\"gloss-ref skill-italic\" data-ref=\"glossary-animal-handling\">Animal Handling</a>, <a href=\"#\" class=\"gloss-ref skill-italic\" data-ref=\"glossary-insight\">Insight</a>, <a href=\"#\" class=\"gloss-ref skill-italic\" data-ref=\"glossary-medicine\">Medicine</a>, <a href=\"#\" class=\"gloss-ref skill-italic\" data-ref=\"glossary-perception\">Perception</a>, <a href=\"#\" class=\"gloss-ref skill-italic\" data-ref=\"glossary-survival\">Survival</a></p><p><strong class=\"skill-label-large\"><a href=\"#\" class=\"gloss-ref\" data-ref=\"glossary-charisma\">Charisma</a>:</strong> <a href=\"#\" class=\"gloss-ref skill-italic\" data-ref=\"glossary-deception\">Deception</a>, <a href=\"#\" class=\"gloss-ref skill-italic\" data-ref=\"glossary-intimidation\">Intimidation</a>, <a href=\"#\" class=\"gloss-ref skill-italic\" data-ref=\"glossary-performance\">Performance</a>, <a href=\"#\" class=\"gloss-ref skill-italic\" data-ref=\"glossary-persuasion\">Persuasion</a></p>"},
  {"id": "dropCreatureTypes", "title": "Creature Types by Skill", "html": "<p><strong class=\"skill-label-large\"><a href=\"#\" class=\"gloss-ref\" data-ref=\"glossary-arcana\">Arcana</a>:</strong> <a href=\"#\" class=\"gloss-ref skill-italic\" data-ref=\"creature-type-aberration\">Aberration</a>, <a href=\"#\" class=\"gloss-ref skill-italic\" data-ref=\"creature-type-construct\">Construct</a>, <a href=\"#\" class=\"gloss-ref skill-italic\" data-ref=\"creature-type-elemental\">Elemental</a>, <a href=\"#\" class=\"gloss-ref skill-italic\" data-ref=\"creature-type-fey\">Fey</a>, <a href=\"#\" class=\"gloss-ref skill-italic\" data-ref=\"creature-type-monstrosity\">Monstrosity</a></p><p><strong class=\"skill-label-large\"><a href=\"#\" class=\"gloss-ref\" data-ref=\"glossary-history\">History</a> / <a href=\"#\" class=\"gloss-ref\" data-ref=\"glossary-medicine\">Medicine</a>:</strong> <a href=\"#\" class=\"gloss-ref skill-italic\" data-ref=\"creature-type-giant\">Giant</a>, <a href=\"#\" class=\"gloss-ref skill-italic\" data-ref=\"creature-type-humanoid\">Humanoid</a></p><p><strong class=\"skill-label-large\"><a href=\"#\" class=\"gloss-ref\" data-ref=\"glossary-nature\">Nature</a>:</strong> <a href=\"#\" class=\"gloss-ref skill-italic\" data-ref=\"creature-type-beast\">Beast</a>, <a href=\"#\" class=\"gloss-ref skill-italic\" data-ref=\"creature-type-dragon\">Dragon</a>, <a href=\"#\" class=\"gloss-ref skill-italic\" data-ref=\"creature-type-ooze\">Ooze</a>, <a href=\"#\" class=\"gloss-ref skill-italic\" data-ref=\"creature-type-plant\">Plant</a></p><p><strong class=\"skill-label-large\"><a href=\"#\" class=\"gloss-ref\" data-ref=\"glossary-religion\">Religion</a>:</strong> <a href=\"#\" class=\"gloss-ref skill-italic\" data-ref=\"creature-type-celestial\">Celestial</a>, <a href=\"#\" class=\"gloss-ref skill-italic\" data-ref=\"creature-type-fiend\">Fiend</a>, <a href=\"#\" class=\"gloss-ref skill-italic\" data-ref=\"creature-type-undead\">Undead</a></p>"},
  {"id": "dropCover", "title": "Cover", "html": "<p><a href=\"#\" class=\"gloss-ref\" data-ref=\"glossary-half-cover\"><strong>Half Cover</strong></a> = +2 <a href=\"#\" class=\"gloss-ref\" data-ref=\"glossary-armor-class\">AC</a> and <a href=\"#\" class=\"gloss-ref\" data-ref=\"glossary-dexterity\">Dexterity</a> <a href=\"#\" class=\"gloss-ref\" data-ref=\"glossary-saving-throw\">Saving Throw</a></p><p><a href=\"#\" class=\"gloss-ref\" data-ref=\"glossary-three-quarters-cover\"><strong>Three-Quarters Cover</strong></a> = +5 <a href=\"#\" class=\"gloss-ref\" data-ref=\"glossary-armor-class\">AC</a> and <a href=\"#\" class=\"gloss-ref\" data-ref=\"glossary-dexterity\">Dexterity</a> <a href=\"#\" class=\"gloss-ref\" data-ref=\"glossary-saving-throw\">Saving Throw</a></p><p><a href=\"#\" class=\"gloss-ref\" data-ref=\"glossary-total-cover\"><strong>Total Cover</strong></a> = Can't be targeted directly</p>"},
  {"id": "dropObscured", "title": "Obscured", "html": "<p><strong><a href=\"#\" class=\"gloss-ref\" data-ref=\"glossary-lightly-obscured\">Lightly Obscured</a></strong> = Disadvantage on <a href=\"#\" class=\"gloss-ref\" data-ref=\"glossary-wisdom\">Wisdom</a> (<a href=\"#\" class=\"gloss-ref\" data-ref=\"glossary-perception\">Perception</a>) <a href=\"#\" class=\"gloss-ref\" data-ref=\"glossary-ability-check\">checks</a> that rely on sight</p><p><strong><a href=\"#\" class=\"gloss-ref\" data-ref=\"glossary-heavily-obscured\">Heavily Obscured</a></strong> = You have the <a href=\"#\" class=\"gloss-ref\" data-ref=\"condition-blinded\">Blinded</a> condition while trying to see something in the area</p>"}
]};
