/* =========================================================
   RULES DATA
   Content for five of the six entries inside the "Rules"
   dropdown in the Reference pane — Ability Score Modifiers,
   Cover, Creature Types by Skill, Obscured, and Skills by
   Ability. (The sixth entry, Jumping, has a live calculator
   built from real inputs/buttons, so it stays hand-written
   directly in index.html rather than living here as data — see
   id="dropJumping" there.) Same {intro, entries:[{id, title,
   html}]} shape as the other *-data.js files.

   ORDER: the entries below are listed alphabetically by title,
   which is also the order they render in. dm-screen.js's
   renderRulesSection() slots the hand-written Jumping dropdown
   into its correct alphabetical position (between "Creature
   Types by Skill" and "Obscured") by comparing each entry's
   title against "Jumping" — so as long as this array stays
   alphabetically sorted, Jumping will always land in the right
   place without needing to be listed here itself.
   ========================================================= */

const RULES_DATA = {"intro": "", "entries": [
  {"id": "dropAbilityScoreModifiers", "title": "Ability Score Modifiers", "html": "<p>To determine an <a href=\"#\" class=\"gloss-ref\" data-ref=\"glossary-ability-score\">ability score</a> modifier, subtract 10 from the ability score and then divide the result by 2 (round down).</p><table class=\"humanoid-grid\"><thead><tr><th>Score</th><th>Modifier</th><th>Score</th><th>Modifier</th></tr></thead><tbody><tr><td>1</td><td>-5</td><td>16-17</td><td>+3</td></tr><tr><td>2-3</td><td>-4</td><td>18-19</td><td>+4</td></tr><tr><td>4-5</td><td>-3</td><td>20-21</td><td>+5</td></tr><tr><td>6-7</td><td>-2</td><td>22-23</td><td>+6</td></tr><tr><td>8-9</td><td>-1</td><td>24-25</td><td>+7</td></tr><tr><td>10-11</td><td>0</td><td>26-27</td><td>+8</td></tr><tr><td>12-13</td><td>+1</td><td>28-29</td><td>+9</td></tr><tr><td>14-15</td><td>+2</td><td>30</td><td>+10</td></tr></tbody></table>"},
  {"id": "dropCover", "title": "Cover", "html": "<p><a href=\"#\" class=\"gloss-ref\" data-ref=\"glossary-half-cover\"><strong>Half Cover</strong></a> = +2 <a href=\"#\" class=\"gloss-ref\" data-ref=\"glossary-armor-class\">AC</a> and <a href=\"#\" class=\"gloss-ref\" data-ref=\"glossary-dexterity\">Dexterity</a> <a href=\"#\" class=\"gloss-ref\" data-ref=\"glossary-saving-throw\">Saving Throw</a></p><p><a href=\"#\" class=\"gloss-ref\" data-ref=\"glossary-three-quarters-cover\"><strong>Three-Quarters Cover</strong></a> = +5 <a href=\"#\" class=\"gloss-ref\" data-ref=\"glossary-armor-class\">AC</a> and <a href=\"#\" class=\"gloss-ref\" data-ref=\"glossary-dexterity\">Dexterity</a> <a href=\"#\" class=\"gloss-ref\" data-ref=\"glossary-saving-throw\">Saving Throw</a></p><p><a href=\"#\" class=\"gloss-ref\" data-ref=\"glossary-total-cover\"><strong>Total Cover</strong></a> = Can't be targeted directly</p>"},
  {"id": "dropCreatureTypes", "title": "Creature Types by Skill", "html": "<p><strong class=\"skill-label-large\"><a href=\"#\" class=\"gloss-ref\" data-ref=\"glossary-arcana\">Arcana</a>:</strong> <a href=\"#\" class=\"gloss-ref skill-italic\" data-ref=\"creature-type-aberration\">Aberration</a>, <a href=\"#\" class=\"gloss-ref skill-italic\" data-ref=\"creature-type-construct\">Construct</a>, <a href=\"#\" class=\"gloss-ref skill-italic\" data-ref=\"creature-type-elemental\">Elemental</a>, <a href=\"#\" class=\"gloss-ref skill-italic\" data-ref=\"creature-type-fey\">Fey</a>, <a href=\"#\" class=\"gloss-ref skill-italic\" data-ref=\"creature-type-monstrosity\">Monstrosity</a></p><p><strong class=\"skill-label-large\"><a href=\"#\" class=\"gloss-ref\" data-ref=\"glossary-history\">History</a> / <a href=\"#\" class=\"gloss-ref\" data-ref=\"glossary-medicine\">Medicine</a>:</strong> <a href=\"#\" class=\"gloss-ref skill-italic\" data-ref=\"creature-type-giant\">Giant</a>, <a href=\"#\" class=\"gloss-ref skill-italic\" data-ref=\"creature-type-humanoid\">Humanoid</a></p><p><strong class=\"skill-label-large\"><a href=\"#\" class=\"gloss-ref\" data-ref=\"glossary-nature\">Nature</a>:</strong> <a href=\"#\" class=\"gloss-ref skill-italic\" data-ref=\"creature-type-beast\">Beast</a>, <a href=\"#\" class=\"gloss-ref skill-italic\" data-ref=\"creature-type-dragon\">Dragon</a>, <a href=\"#\" class=\"gloss-ref skill-italic\" data-ref=\"creature-type-ooze\">Ooze</a>, <a href=\"#\" class=\"gloss-ref skill-italic\" data-ref=\"creature-type-plant\">Plant</a></p><p><strong class=\"skill-label-large\"><a href=\"#\" class=\"gloss-ref\" data-ref=\"glossary-religion\">Religion</a>:</strong> <a href=\"#\" class=\"gloss-ref skill-italic\" data-ref=\"creature-type-celestial\">Celestial</a>, <a href=\"#\" class=\"gloss-ref skill-italic\" data-ref=\"creature-type-fiend\">Fiend</a>, <a href=\"#\" class=\"gloss-ref skill-italic\" data-ref=\"creature-type-undead\">Undead</a></p>"},
  {"id": "dropObscured", "title": "Obscured", "html": "<p><strong><a href=\"#\" class=\"gloss-ref\" data-ref=\"glossary-lightly-obscured\">Lightly Obscured</a></strong> = Disadvantage on <a href=\"#\" class=\"gloss-ref\" data-ref=\"glossary-wisdom\">Wisdom</a> (<a href=\"#\" class=\"gloss-ref\" data-ref=\"glossary-perception\">Perception</a>) <a href=\"#\" class=\"gloss-ref\" data-ref=\"glossary-ability-check\">checks</a> that rely on sight</p><p><strong><a href=\"#\" class=\"gloss-ref\" data-ref=\"glossary-heavily-obscured\">Heavily Obscured</a></strong> = You have the <a href=\"#\" class=\"gloss-ref\" data-ref=\"condition-blinded\">Blinded</a> condition while trying to see something in the area</p>"},
  {"id": "dropSkills", "title": "Skills by Ability", "html": "<p><strong class=\"skill-label-large\"><a href=\"#\" class=\"gloss-ref\" data-ref=\"glossary-strength\">Strength</a>:</strong> <a href=\"#\" class=\"gloss-ref skill-italic\" data-ref=\"glossary-athletics\">Athletics</a></p><p><strong class=\"skill-label-large\"><a href=\"#\" class=\"gloss-ref\" data-ref=\"glossary-dexterity\">Dexterity</a>:</strong> <a href=\"#\" class=\"gloss-ref skill-italic\" data-ref=\"glossary-acrobatics\">Acrobatics</a>, <a href=\"#\" class=\"gloss-ref skill-italic\" data-ref=\"glossary-sleight-of-hand\">Sleight of Hand</a>, <a href=\"#\" class=\"gloss-ref skill-italic\" data-ref=\"glossary-stealth\">Stealth</a></p><p><strong class=\"skill-label-large\"><a href=\"#\" class=\"gloss-ref\" data-ref=\"glossary-intelligence\">Intelligence</a>:</strong> <a href=\"#\" class=\"gloss-ref skill-italic\" data-ref=\"glossary-arcana\">Arcana</a>, <a href=\"#\" class=\"gloss-ref skill-italic\" data-ref=\"glossary-history\">History</a>, <a href=\"#\" class=\"gloss-ref skill-italic\" data-ref=\"glossary-investigation\">Investigation</a>, <a href=\"#\" class=\"gloss-ref skill-italic\" data-ref=\"glossary-nature\">Nature</a>, <a href=\"#\" class=\"gloss-ref skill-italic\" data-ref=\"glossary-religion\">Religion</a></p><p><strong class=\"skill-label-large\"><a href=\"#\" class=\"gloss-ref\" data-ref=\"glossary-wisdom\">Wisdom</a>:</strong> <a href=\"#\" class=\"gloss-ref skill-italic\" data-ref=\"glossary-animal-handling\">Animal Handling</a>, <a href=\"#\" class=\"gloss-ref skill-italic\" data-ref=\"glossary-insight\">Insight</a>, <a href=\"#\" class=\"gloss-ref skill-italic\" data-ref=\"glossary-medicine\">Medicine</a>, <a href=\"#\" class=\"gloss-ref skill-italic\" data-ref=\"glossary-perception\">Perception</a>, <a href=\"#\" class=\"gloss-ref skill-italic\" data-ref=\"glossary-survival\">Survival</a></p><p><strong class=\"skill-label-large\"><a href=\"#\" class=\"gloss-ref\" data-ref=\"glossary-charisma\">Charisma</a>:</strong> <a href=\"#\" class=\"gloss-ref skill-italic\" data-ref=\"glossary-deception\">Deception</a>, <a href=\"#\" class=\"gloss-ref skill-italic\" data-ref=\"glossary-intimidation\">Intimidation</a>, <a href=\"#\" class=\"gloss-ref skill-italic\" data-ref=\"glossary-performance\">Performance</a>, <a href=\"#\" class=\"gloss-ref skill-italic\" data-ref=\"glossary-persuasion\">Persuasion</a></p>"}
]};
